### ISSUE TITLE
How to use css3 background patterns?

### ISSUE THREAD

**Issue by juliankim** [jshimko/telescope-plugin-hero#6]
http://lea.verou.me/css3patterns/#cicada-stripes
I thought this pattern was pretty sick so I put the code in ExtraCSS

This is what I put
.hero {
background-color: #026873;
background-image: linear-gradient(90deg, rgba(255,255,255,.07) 50%, transparent 50%),
linear-gradient(90deg, rgba(255,255,255,.13) 50%, transparent 50%),
linear-gradient(90deg, transparent 50%, rgba(255,255,255,.17) 50%),
linear-gradient(90deg, transparent 50%, rgba(255,255,255,.19) 50%);
background-size: 13px, 29px, 37px, 53px;
}

Didn't work, [background-color] seem to work but nothing else. So as other css patterns.

**Comment by jshimko** [comment]
This isn't really an issue with the plugin.  You likely need some vendor prefixes.  

At the very least...

``` css
.hero {
  background-color: #026873;
  background-image: -webkit-linear-gradient(0deg, rgba(255,255,255,.07) 50%, transparent 50%), 
                    -webkit-linear-gradient(0deg, rgba(255,255,255,.13) 50%, transparent 50%), 
                    -webkit-linear-gradient(0deg, transparent 50%, rgba(255,255,255,.17) 50%), 
                    -webkit-linear-gradient(0deg, transparent 50%, rgba(255,255,255,.19) 50%);
  background-image: linear-gradient(90deg, rgba(255,255,255,.07) 50%, transparent 50%),
                    linear-gradient(90deg, rgba(255,255,255,.13) 50%, transparent 50%),
                    linear-gradient(90deg, transparent 50%, rgba(255,255,255,.17) 50%),
                    linear-gradient(90deg, transparent 50%, rgba(255,255,255,.19) 50%);
  background-size: 13px, 29px, 37px, 53px;
}
```

**Comment by juliankim** [comment]
Still isn't working :(... I'll figure it out

**Comment by jshimko** [comment]
``` css
.hero .hero-inner {
  background-image: -webkit-linear-gradient(0deg, rgba(255,255,255,.07) 50%, transparent 50%), 
                    -webkit-linear-gradient(0deg, rgba(255,255,255,.13) 50%, transparent 50%), 
                    -webkit-linear-gradient(0deg, transparent 50%, rgba(255,255,255,.17) 50%), 
                    -webkit-linear-gradient(0deg, transparent 50%, rgba(255,255,255,.19) 50%);
  background-image: linear-gradient(90deg, rgba(255, 255, 255, 0.0666667) 50%, transparent 50%), 
                    linear-gradient(90deg, rgba(255, 255, 255, 0.129412) 50%, transparent 50%), 
                    linear-gradient(90deg, transparent 50%, rgba(255, 255, 255, 0.168627) 50%), 
                    linear-gradient(90deg, transparent 50%, rgba(255, 255, 255, 0.188235) 50%);
  background-color: rgb(2, 104, 115);
  background-size: 13px, 29px, 37px, 53px;
}
```
